chore: add CONTRIBUTING.md page to Dialtone Icons
dialpad/dialtone pull request #105
Opened 2024-01-17 18:35 UTC by ninamarina

# PR Title

## Obligatory GIF (super important!)

![Obligatory GIF](path/to/gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ ] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script.
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [ ] I have considered how this change will behave on different screen sizes.
- [ ] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

If new component:

- I am exporting any new components or constants:
  - [ ] from the index.js in the component directory.
  - [ ] from the index.js in the root (either `packages/dialtone-vue2` or `packages/dialtone-vue3`).
- [ ] I have added the styles for the new component to the `packages/dialtone-css` package.
- [ ] I have created a page for the new component on the documentation site in `apps/dialtone-documentation`.
- [ ] I have added the new component to `common/components_list.cjs` in `packages/dialtone-vue2` and `packages/dialtone-vue3`
- [ ] I have created a component story in storybook
- [ ] I have created story / stories for any relevant component variants in storybook
- [ ] I have created a docs page for the component in storybook.
- [ ] I have checked that changing all props/slots via the UI in storybook works as expected.

## :crystal_ball: Next Steps

## :camera: Screenshots / GIFs

## :link: Sources

2024-01-18 17:12 UTC, iropolo approved these changes
Looks, Ok, wait for a design review @yorbi-dp @fede-dp

2024-01-18 18:48 UTC, braddialpad approved these changes
Looks fine to me though a lot of this stuff is repeated in multiple documents (roles, commit convention, etc) Wondering if we should move this stuff to the parent document. Anyways, that's outside the scope of this PR, this looks good.

2024-01-19 15:30 UTC, yorbi-dp reviewed
Nice we can include the contribution info for this packages! Thanks Nina! 😄

2024-01-19 15:53 UTC, ninamarina commented
> Looks fine to me though a lot of this stuff is repeated in multiple documents (roles, commit convention, etc) Wondering if we should move this stuff to the parent document. Anyways, that's outside the scope of this PR, this looks good.

I agree all this page could be summarized. Probably the most important section is this one: https://github.com/dialpad/dialtone/pull/105/files#diff-2e26192c13c3c1ef3e307cf5fe07dbff0f1c9ad42ea0ca2d3e0e1e7e509c5158R65
And all the other info is more generic to the repo

2024-01-19 16:11 UTC, yorbi-dp requested changes

2024-01-19 16:11 UTC, yorbi-dp commented on packages/dialtone-icons/.github/CONTRIBUTING.md
> +- `icons.json`: Contains the categories on which icons are going to be included and the keywords to make the icons more discoverable while searching on [Dialtone icons documentation](https://dialpad.
It's `keywords.json` the file with the categories and keywords.

2024-01-19 16:11 UTC, yorbi-dp commented on packages/dialtone-icons/.github/CONTRIBUTING.md
> +
Should we add the step-by-step to add an icon in the package?
- In the [Icons Figma file](https://www.figma.com/file/zz40wi0uW9MvaJ5RuhcRZR/DT9-Icon-Library?type=design&node-id=10023-2864&mode=design&t=zfm4YTgkSdohnCrw-4) select and export each icon as SVG. 
- Place the exported SVG file(s) in the appropriate folder category inside `./src/svg/`
- Run `pnpm run build` adding the name and keywords in the `keywords.json` file.
- Add the keywords array as the value. e.g.
```
{
   "arrows": {
     "arrow-left": ["arrow", "left", "direction"],
     ...
   }
}
``` 
- Add, commit and push your changes as mentioned from step 4 in [Making a pull request](#making-a-pull-request).
- Open a pull request.
- Once approved it can be merged into main and will go out in the next `dialtone` release.

[Learn more on How to craft an icon.](https://dialtone.dialpad.com/design/icons/#crafting-an-icon)

Not sure where should this be?

2024-01-19 16:11 UTC, yorbi-dp commented on packages/dialtone-icons/.github/CONTRIBUTING.md
> +or standalone as SVG files
We can add something like:
[Check the Icon catalog](https://dialtone.dialpad.com/design/icons/)

2024-01-19 18:29 UTC, ninamarina commented on packages/dialtone-icons/.github/CONTRIBUTING.md
> +
Added this info in a new section "Adding an icon"

2024-01-19 19:20 UTC, yorbi-dp approved these changes
LGTM! Thank you Nina! 🙌

2024-01-22 13:35 UTC, merged