feat: new icon user speak
dialpad/dialtone pull request #147
Opened 2024-02-08 19:18 UTC by fede-dp

# feat: new icon user speak

## Obligatory GIF (super important!)

![Obligatory GIF](https://media.giphy.com/media/26FeYmOzYoQHT7ko8/giphy.gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [x ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ x] I have reviewed my changes.
- [x ] I have added all relevant documentation.
- [ x] I have considered the performance impact of my change.

2024-02-08 19:37 UTC, yorbi-dp requested changes
It's missing the `run build` to create or add the icon in the keywords.json

2024-02-09 04:26 UTC, francisrupert commented on packages/dialtone-icons/src/svg/people/user-speak.svg
Maybe `user-speak`? If only to align to other "user" icons, i.e. https://dialtone.dialpad.com/design/icons/?search=user

Definitely needs `keywords.json` added.

2024-02-09 04:27 UTC, francisrupert commented on packages/dialtone-icons/src/svg/people/user-speak.svg
Oh never mind, I'm an idiot. That is the name you used 🙃

2024-02-09 20:54 UTC, yorbi-dp approved these changes
LGTM!

2024-02-09 21:04 UTC, fede-dp commented
> LGTM!

was trying to change the icon from marshall proposal that Francis suggested in the figma, i think is ready now!

2024-02-09 22:58 UTC, braddialpad approved these changes

2024-02-12 21:20 UTC, merged