feat: transform Figma variables to sd format
dialpad/dialtone pull request #154
Opened 2024-02-13 19:05 UTC by juliodialpad

# Feat: transform Figma variables to sd format

## Obligatory GIF (super important!)

![Obligatory GIF](https://media.giphy.com/media/xI71J7AVBozv2/giphy.gif?cid=82a1493brdgjidv7n65anlq2m9dj73v4whecmd7djc86lsu9&ep=v1_gifs_trending&rid=giphy.gif&ct=g)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

## :book: Jira Ticket

No Jira Ticket

## :book: Description

- Added custom type (`sizing`, `spacing`, etc) after getting tokens from Figma to match our current implementation
- Added a transformation script that reads base and root files on `figma_tokens` directory, iterates through it and replaces the values accordingly.
- Currently that script is very focused on just reading those two files as it's the only I have currently, but can be adapted in the future to read any number of files.

## :bulb: Context

- We're moving forward into using Figma variables API, with this, we can actually start syncing sizing and spacing variables from Figma
- Syncing from the code to Figma it's possible now but we still need to standardize a way to do this to avoid confusions on what files need to be modified.

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

## :crystal_ball: Next Steps

- Standardize and document a way to sync tokens to Figma

2024-02-14 15:57 UTC, francisrupert commented
@juliodialpad I've added @yorbi-dp as a reviewer. Since he wouldn't directly PR review the code, the two of you should figure out a way that most makes sense for him to review and confirm the **resulting** CSS variables are unchanged.

2024-02-20 01:39 UTC, yorbi-dp requested changes
This looks great Tico! Nice work 😃 everything it's matching the current tokens and these new ones created from the Figma Variables.
- Just the token  `--dt-size-radius-circle` has a different value. Left a comment in the [evidence google sheet.](https://docs.google.com/spreadsheets/d/1H1pBc9m_cfIWbKgEEtaqxKiwTes5sBcjLAFX19rXVM8/edit#gid=0)

2024-02-20 22:24 UTC, yorbi-dp approved these changes
LGTM! Thank you!! 🙌

2024-02-21 00:37 UTC, braddialpad approved these changes
Looks pretty good. Couple comments but approving, this is good to go.

2024-02-21 00:37 UTC, braddialpad commented on packages/dialtone-tokens/.eslintrc.cjs
We need typescript?

2024-02-21 00:37 UTC, braddialpad commented on packages/dialtone-tokens/dialtone-transforms.js
> +    return '0rem';
didn't you say you wanted this to be 0 instead of 0rem?

2024-02-21 00:37 UTC, braddialpad commented on packages/dialtone-tokens/sync-scripts/token_export.ts
> +}
Not that big of deal, but would an object map work better?

```
customTypeMap = {
  'space': 'spacing'
  'size': {
    border: 'borderWidth'
    ....
  }
}

// use like this
const variableNames = variable.name.split('/');
customTypeMap[variableNames[0]][variableNames[1]]
```

Your call if you like it better or not.

2024-02-21 01:20 UTC, juliodialpad commented on packages/dialtone-tokens/.eslintrc.cjs
Just wanted to match the Figma provided scripts, I was having some weird errors about importing JS on a TS file so decided to change the script to TS (not fully migrated, just to enough to get rid of errors).

2024-02-21 01:21 UTC, juliodialpad commented on packages/dialtone-tokens/dialtone-transforms.js
> +    return '0rem';
The other way around, the staging css output had `0rem` and after my changes the output was just `0` so added that to always have `0rem` on sizing and spacing.

2024-02-21 01:22 UTC, juliodialpad commented on packages/dialtone-tokens/sync-scripts/token_export.ts
> +}
For sure I prefer the object map, I'll update it

2024-02-21 21:28 UTC, braddialpad approved these changes

2024-02-22 20:01 UTC, merged