feat: added new customize icon
dialpad/dialtone pull request #161
Opened 2024-02-20 15:58 UTC by yorbi-dp

# feat: added new customize icon

## Obligatory GIF (super important!)

![Obligatory GIF](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNmo2c3hvMGI1ZTNmaGY5ZjdxZWczcGJ0ZmtpYXdhMmlnZjVyaTJ0YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/S1y950todEVbYqUQlE/giphy.gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1561

2024-02-20 16:02 UTC, francisrupert approved these changes

2024-02-20 18:36 UTC, iropolo approved these changes
Thanks!!

2024-02-20 19:44 UTC, francisrupert requested changes
Resolve our offline questions first.

2024-02-21 20:06 UTC, closed without merging

2024-02-21 20:06 UTC, yorbi-dp commented
We won't be adding this icon.