feat. adding new blog for Types update
dialpad/dialtone pull request #222
Opened 2024-03-21 17:32 UTC by yorbi-dp

# PR Title

## Obligatory GIF (super important!)

![Obligatory GIF](path/to/gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ ] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script.
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [ ] I have considered how this change will behave on different screen sizes.
- [ ] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

If new component:

- I am exporting any new components or constants:
  - [ ] from the index.js in the component directory.
  - [ ] from the index.js in the root (either `packages/dialtone-vue2` or `packages/dialtone-vue3`).
- [ ] I have added the styles for the new component to the `packages/dialtone-css` package.
- [ ] I have created a page for the new component on the documentation site in `apps/dialtone-documentation`.
- [ ] I have added the new component to `common/components_list.cjs` in `packages/dialtone-vue2` and `packages/dialtone-vue3`
- [ ] I have created a component story in storybook
- [ ] I have created story / stories for any relevant component variants in storybook
- [ ] I have created a docs page for the component in storybook.
- [ ] I have checked that changing all props/slots via the UI in storybook works as expected.

## :crystal_ball: Next Steps

## :camera: Screenshots / GIFs

## :link: Sources

2024-03-21 17:53 UTC, francisrupert commented
👀 Oooh niiice. I'll refrain from reviewing yet since you have it as as Draft. But dang, this is beyond what I hoped for. 💪

2024-03-21 22:17 UTC, francisrupert requested changes
Awesome stuff. A few copy tweaks, and correction of CSS Utility names (e.g. `d-label-md` → `d-label--md`).

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +**TL;DR:** We're rolling out an important update to our Typography Tokens set, which involves a significant renaming of Design Tokens.
Recommended:

```md
We're rolling out an important update to Dialtone [Typography Styles](path/to/design/typography#styles) based on an adjustment to our Design Tokens naming convention.
```

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +Our previous naming convention, while functional, lacked uniformity and clarity. Also overlapping groups, causing unnecessary complexity. By refining the naming structure, we're making it easier for
Suggested:

```md
Our previous naming convention, while functional, lacked uniformity and clarity. In particular, its previous naming convention caused unnecessary complexity and lacked a predictable naming pattern. By refining the naming structure, we've making it easier for you to locate and utilize the styles you need in HTML, Vue, CSS, Figma deliverables, or otherwise.
```

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +- **Aligned Across Platforms,** we align Figma styles with CSS Utilities and CSS Variables, making integration smoother and collaboration better.
Suggested:
```md
- **Aligned Across Platforms,** Figma styles more strictly match the naming convention of CSS Utilities and CSS Variables, making integration smoother and collaboration better.
```

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +We'll maintain support for the old naming convention until the end of 2024. However, we encourage you to begin updating your projects to the new convention for a seamless experience.
Suggested:

```md
Backwards-compatible support for the previous CSS Utilities will remain for the near-term. However, we encourage you to begin updating your projects to the new convention for a seamless experience.
```

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +        <td class="d-bgc-black-100"><code class="d-code--sm">headline-eyebrow</code></td>
`d-bgc-secondary` in place of `d-bgc-black-100`

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +    </tbody>
Both columns: pre `d-` to each CSS Utility.

New column: note the naming convention's use of `--` (double-dash) after the category. e.g. `headline-sm-soft` → `d-headline--sm-soft`.

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +When working with [Figma for VS Code](https://help.figma.com/hc/en-us/articles/15023121296151-Figma-for-VS-Code) or using [Dev Mode](https://help.figma.com/hc/en-us/articles/15023124644247-Guide-to-D
"...elements.Simply replace...` → "...elements. Simply replace...` (space between "Simply".

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +You might notice prompts to update the library in your files. Fear not – this update won't alter any styles. We've even added descriptions for each style to guide you through the process. Plus, we've
Suggested:

```md
... We've even added searchable descriptions to each style to improve findability. For example, searching for `medium` will find text styles like `typography/body/md` and `typography/headline/md`. Plus, we've introduced..."
```

2024-03-21 22:17 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +- CSS Utilities `d-label-md`
`d-label--md` (double-dash).

2024-03-21 22:38 UTC, braddialpad reviewed
Super well written and detailed. Couple tiny things.

2024-03-21 22:38 UTC, braddialpad commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +- **Simplified CSS usage,** now all types are name with this structure: `d-{category}--{size}-{strength*}-{density*}`, e.g. `d-body-compact-small`
all types are named

2024-03-21 22:38 UTC, braddialpad commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +Update any references of `var(--dt-typography...)` with the updated equivalents. Refer to the mapping table for clarity.
show a full example of the migration just to avoid any confusion:

```
var(--dt-typography-body-base) -> var(--dt-typography-body-md)
```

2024-03-21 22:38 UTC, braddialpad commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +Replace any instances of the old naming convention with the corresponding new names. Refer to the mapping table for clarity.
show an example for the CSS utilities as well

```
class="d-label-plain-small" -> class="d-label-sm-plain"
```

2024-03-22 14:34 UTC, yorbi-dp commented
@francisrupert @braddialpad Thank you so much for all the feedback! 🙌 I just pushed an updated version of the post. Let me know your thoughts!

2024-03-22 16:31 UTC, francisrupert approved these changes
Approving, though with a couple tiny changes.

2024-03-22 16:31 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +- CSS Utilities `d-label-md`
This didn't update.

2024-03-22 16:31 UTC, francisrupert commented on apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
> +![Updates on Typography Tokens](/assets/images/new_types_cover_1.gif)
![image](https://github.com/dialpad/dialtone/assets/1165933/ca5968d3-60ce-4348-8802-8543528a46a2)

2024-03-22 17:37 UTC, merged