feat(rich-text-editor): DLT-1598 add slash commands suggestions
dialpad/dialtone pull request #284
Opened 2024-04-25 13:58 UTC by ninamarina

# PR Title

## Obligatory GIF (super important!)

![Obligatory GIF](path/to/gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ ] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script.
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [ ] I have considered how this change will behave on different screen sizes.
- [ ] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

If new component:

- I am exporting any new components or constants:
  - [ ] from the index.js in the component directory.
  - [ ] from the index.js in the root (either `packages/dialtone-vue2` or `packages/dialtone-vue3`).
- [ ] I have added the styles for the new component to the `packages/dialtone-css` package.
- [ ] I have created a page for the new component on the documentation site in `apps/dialtone-documentation`.
- [ ] I have added the new component to `common/components_list.cjs`
- [ ] I have created a component story in storybook
- [ ] I have created story / stories for any relevant component variants in storybook
- [ ] I have created a docs page for the component in storybook.
- [ ] I have checked that changing all props/slots via the UI in storybook works as expected.

## :crystal_ball: Next Steps

## :camera: Screenshots / GIFs

## :link: Sources

2024-04-26 22:59 UTC, braddialpad commented
Some flakiness on percy.. seems to have nothing to do with your change.

2024-04-26 23:07 UTC, braddialpad requested changes
Couple of edge cases, looks pretty good otherwise

2024-04-26 23:07 UTC, braddialpad commented on packages/dialtone-vue2/components/rich_text_editor/extensions/slash_command/SlashCommandSuggestion.vue
If I type /giphy and press enter it breaks to the next line instead of just confirming and putting a space

2024-04-26 23:07 UTC, braddialpad commented on packages/dialtone-vue2/components/rich_text_editor/extensions/slash_command/SlashCommandSuggestion.vue
If I type out /meeting and then go down and select /meeting2 from the dropdown it inputs /meeting instead /meeting2. Probably because /meeting is a valid slash command

2024-04-26 23:10 UTC, braddialpad commented
Getting an error in rich-text-editor "with mention suggestions" variant in storybook when I type an @ and select one of the options

2024-04-26 23:15 UTC, juliodialpad commented
> Some flakiness on percy.. seems to have nothing to do with your change.

That's my fault, added the config back to made them reliable again on: https://github.com/dialpad/dialtone/pull/288

2024-04-29 19:30 UTC, juliodialpad commented
Percy is still having some flakiness with emojis, not related to this PR.

2024-04-29 21:05 UTC, braddialpad approved these changes
Nice, looks good by me

2024-04-30 15:49 UTC, merged