feat(icon): DLT-1804 add t-mobile
dialpad/dialtone pull request #387
Opened 2024-06-28 13:49 UTC by fede-dp

# DLT-1804 add t-mobile

## Obligatory GIF (super important!)

![Obligatory GIF](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2hnYWVud2Q4Y2E2cGI4eWk2MXI4MGt6bTFlMXUwZzkzaHV5MXJ4ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/bKZB5Qw2nRNtIDhS6s/giphy.gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

DLT-1834(https://dialpad.atlassian.net/browse/DLT-1834)

## :book: Description

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

## :camera: Screenshots / GIFs

![image](https://github.com/dialpad/dialtone/assets/135134059/65200f6c-9638-4d06-b01b-304517f2bc98)

2024-06-28 13:58 UTC, francisrupert approved these changes
I approve from Design perspective. Before merging, resolve my question about `icons.json` from a DT engineer.

2024-06-28 13:58 UTC, francisrupert commented on packages/dialtone-icons/src/icons.json
I'm unclear on this file. Obviously it's autogenerated, but it seems to be new... for what reason? Who can answer that @juliodialpad perhaps?

2024-06-28 13:58 UTC, francisrupert commented on packages/dialtone-icons/src/keywords-icons.json
> +        "tmo"
Perfect keyword.

2024-06-28 14:14 UTC, iropolo commented on packages/dialtone-icons/src/icons.json
That file should not be included in this PR, not sure why it is there but it is not in our main branch.
It is not part of the workflow.

2024-06-28 14:16 UTC, iropolo requested changes
Remove `icons.json`.

The rest looks fine.

2024-06-28 16:49 UTC, braddialpad commented on packages/dialtone-icons/src/icons.json
@fede-dp how is this file even showing up. Is it getting generated when you build or run some other process?

2024-06-28 18:57 UTC, fede-dp commented
> Remove `icons.json`.
> 
> The rest looks fine.



> Remove `icons.json`.
> 
> The rest looks fine.



> Remove `icons.json`.
> 
> The rest looks fine.

removed!

2024-06-28 19:44 UTC, braddialpad approved these changes
Looks fine now, any idea what you did to make that file generate?

2024-07-01 00:24 UTC, iropolo approved these changes

2024-07-01 14:52 UTC, merged