chore: remove deprecated d-svg class from component styles
dialpad/dialtone pull request #39
Opened 2023-12-07 17:18 UTC by ninamarina

## Description
Jira: https://dialpad.atlassian.net/browse/DLT-502

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)
![giphy](https://github.com/dialpad/dialtone/assets/24460973/4c0d41c7-cb08-4b17-89ee-9294a1de21be)

2023-12-07 17:26 UTC, ninamarina commented on apps/dialtone-documentation/docs/.vuepress/theme/assets/less/dialtone-docs.less
> -  }
This is not regarding size, but it doesn't seem to be used that's why I removed it. Please corroborate.

2023-12-11 16:14 UTC, iropolo commented
I tried to fire percy action with `visual-test-ready` label

2023-12-11 17:42 UTC, iropolo commented
Would be necessary to update visual_tests GHA

2023-12-11 19:13 UTC, braddialpad requested changes

2023-12-11 19:13 UTC, braddialpad commented on apps/dialtone-documentation/docs/.vuepress/theme/assets/less/dialtone-docs.less
We should probably not change any of the DocSearch stuff. This is used to modify how the algolia search looks. You won't find it if you search the repo because it's only output to the DOM as an external library, the code is not in our codebase. For example changing `.DocSearch-Logo svg` made it look like this:

![Screenshot 2023-12-11 at 10 53 36 AM](https://github.com/dialpad/dialtone/assets/64808812/ce6a6abb-abd2-4b12-a3c1-dca592ebb37c)

As opposed to this:

![Screenshot 2023-12-11 at 10 56 46 AM](https://github.com/dialpad/dialtone/assets/64808812/748b06b6-7aa5-4caa-9536-c8d9c3e4abbe)

2023-12-11 20:04 UTC, ninamarina commented on apps/dialtone-documentation/docs/.vuepress/theme/assets/less/dialtone-docs.less
this makes sense, thanks! just reverted

2023-12-11 20:13 UTC, braddialpad approved these changes

2023-12-11 20:36 UTC, merged