docs: DLT-1897 move SB to doc site - Emoji to Emoji Text Wrapper
dialpad/dialtone pull request #412
Opened 2024-07-23 15:57 UTC by ninamarina

# PR Title

## Obligatory GIF (super important!)

![Obligatory GIF](path/to/gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ ] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [ ] I have considered how this change will behave on different screen sizes.
- [ ] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

If new component:

- I am exporting any new components or constants:
  - [ ] from the index.js in the component directory.
  - [ ] from the index.js in the root (either `packages/dialtone-vue2` or `packages/dialtone-vue3`).
- [ ] I have added the styles for the new component to the `packages/dialtone-css` package.
- [ ] I have created a page for the new component on the documentation site in `apps/dialtone-documentation`.
- [ ] I have added the new component to `common/components_list.cjs`
- [ ] I have created a component story in storybook
- [ ] I have created story / stories for any relevant component variants in storybook
- [ ] I have created a docs page for the component in storybook.
- [ ] I have checked that changing all props/slots via the UI in storybook works as expected.

## :crystal_ball: Next Steps

## :camera: Screenshots / GIFs

## :link: Sources

2024-07-23 21:28 UTC, juliodialpad requested changes
Looking good! small change and some comments left:

Can we center this emojis please? https://dialtone.dialpad.com/deploy-previews/pr-412/components/emoji.html#sizes


<img width="1068" alt="image" src="https://github.com/user-attachments/assets/3ead10e3-b53f-47db-a9e5-8f995f7379ef">

2024-07-23 21:28 UTC, juliodialpad commented on apps/dialtone-documentation/docs/components/emoji-text-wrapper.md
> +// the emoji module in your application.
This is no longer a true statement, emoji-text-wrapper is now part of dialtone-vue

2024-07-23 21:49 UTC, francisrupert commented
> Can we center this emojis please?

Hmm, this actually looks like a bug to me. They technically **are** centered but the rendered image within `.d-emoji` shifts out of its bounding container needs to be block-level to fill the space correctly. 

And of course, ensure this doesn't impact the Emoji Wrapper PR @juliodialpad currently has going. 

https://github.com/user-attachments/assets/43ffbe45-5e2c-405b-8416-cafdb2e8d228

2024-07-24 18:09 UTC, braddialpad commented
@ninamarina let's merge in staging, now that Julio's emoji alignment change is in there.

2024-07-24 20:22 UTC, braddialpad commented
Similar alignment issues here as well:

![Screenshot 2024-07-24 at 1 22 20 PM](https://github.com/user-attachments/assets/5df50534-01ce-4810-99b2-8be8bb3f17b5)

2024-07-24 20:25 UTC, braddialpad commented on apps/dialtone-documentation/docs/components/emoji.md
> +// the emoji module in your application.
Same thing Julio mentioned but in emoji.md file. Can remove this comment

2024-07-24 21:10 UTC, ninamarina commented
To fix the alignment, I applied Julio's fix in the scoped styles of this page. I am assuming putting all sizes of emojis one after the other is not a real use case.

2024-07-24 21:24 UTC, francisrupert commented
> To fix the alignment, I applied the same that Julio did for the emoji text wrapper in the scoped styles

I think this actually needs to be fixed at the item level itself. The rendered emoji `<img>` isn't properly sitting in its bounding container. 

<img width="539" alt="image" src="https://github.com/user-attachments/assets/7214f2e7-1289-4bb6-b5c3-004ca311bd80">

2024-07-25 13:46 UTC, ninamarina commented
> > To fix the alignment, I applied the same that Julio did for the emoji text wrapper in the scoped styles
> 
> I think this actually needs to be fixed at the item level itself. The rendered emoji `<img>` isn't properly sitting in its bounding container.
> 
> <img alt="image" width="539" src="https://private-user-images.githubusercontent.com/1165933/351884951-7214f2e7-1289-4bb6-b5c3-004ca311bd80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTUwNTYsIm5iZiI6MTcyMTkxNDc1NiwicGF0aCI6Ii8xMTY1OTMzLzM1MTg4NDk1MS03MjE0ZjJlNy0xMjg5LTRiYjYtYjVjMy0wMDRjYTMxMWJkODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTMzOTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MThiODJmYmEwOTg4NWYyZGMyYzA1MDFiOTNlZTg3NjE5NmUxZTg4NzdkYjkzYWVhODVmZGNiZmY5NzUxMmE2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xuppb67Aq2uthFSuQcPoYBncVb3Nm63LC5phQBpRYrs">

I created this ticket to fix that: https://dialpad.atlassian.net/browse/DLT-1913
This one is just for moving the docs, so we should address that as a separate bug.

2024-07-25 17:10 UTC, juliodialpad approved these changes
Looking good, thanks Nina!

2024-07-25 17:13 UTC, braddialpad approved these changes
Good by me as well.

2024-07-25 17:33 UTC, merged