Dlt 1991 add sparkle ai icon with gradient
dialpad/dialtone pull request #495
Opened 2024-09-12 14:39 UTC by fede-dp

# PR Title

## Obligatory GIF (super important!)

![Obligatory GIF](path/to/gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ ] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [ ] I have considered how this change will behave on different screen sizes.
- [ ] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

If new component:

- I am exporting any new components or constants:
  - [ ] from the index.js in the component directory.
  - [ ] from the index.js in the root (either `packages/dialtone-vue2` or `packages/dialtone-vue3`).
- [ ] I have added the styles for the new component to the `packages/dialtone-css` package.
- [ ] I have created a page for the new component on the documentation site in `apps/dialtone-documentation`.
- [ ] I have added the new component to `common/components_list.js`
- [ ] I have created a component story in storybook
- [ ] I have created story / stories for any relevant component variants in storybook
- [ ] I have created a docs page for the component in storybook.
- [ ] I have checked that changing all props/slots via the UI in storybook works as expected.

## :crystal_ball: Next Steps

## :camera: Screenshots / GIFs

## :link: Sources

2024-09-12 15:48 UTC, francisrupert requested changes

2024-09-12 15:48 UTC, francisrupert commented on packages/dialtone-icons/src/svg/icons/general/sparkle-filled.svg
<img width="366" alt="image" src="https://github.com/user-attachments/assets/64c12ead-0e86-498a-960b-af2ee4898557">

The placement of the two stars to the right side aren't identical.

2024-09-12 15:48 UTC, francisrupert commented on packages/dialtone-icons/src/keywords-icons.json
> +        "dialpad",
Redundant. Remove.

2024-09-12 15:48 UTC, francisrupert commented on packages/dialtone-icons/src/keywords-icons.json
> +        "spark",
Redundant. Remove.

2024-09-12 15:48 UTC, francisrupert commented on apps/dialtone-documentation/docs/.vuepress/public/assets/images/components/empty-state.svg
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/0ccc365d-ddca-457a-bbce-fc574a6badea">

This is fine for now, but log a new task to redraw this entire thumb:

Background doesn't match others. Colors overall don't feel right at all. It's an extremely busy-looking thumb for a simple component. Simplify it if you can.

2024-09-12 18:22 UTC, francisrupert commented on packages/dialtone-icons/src/svg/icons/general/sparkle-filled.svg
<img width="481" alt="image" src="https://github.com/user-attachments/assets/11b0c157-cbfe-4bf7-9c37-ff137cf5f945">

The position of the two small sparks should match the one of `dialpad-sparkle`. That is, the top spark is slightly to the left of the bottom one.

2024-09-12 18:34 UTC, fede-dp commented on apps/dialtone-documentation/docs/.vuepress/public/assets/images/components/empty-state.svg
solved!

2024-09-12 19:08 UTC, francisrupert commented on packages/dialtone-icons/src/keywords-icons.json
> +      "dialpad-spark": [
```suggestion
      "dialpad-sparkle": [
```

2024-09-12 19:15 UTC, francisrupert commented on packages/dialtone-icons/src/svg/icons/general/sparkle-filled.svg
@fede-dp https://dialtone.dialpad.com/deploy-previews/pr-495/design/icons/?search=sparkle

2024-09-13 13:22 UTC, francisrupert commented on packages/dialtone-icons/src/svg/icons/general/sparkle-filled.svg
Bump

2024-09-13 14:38 UTC, francisrupert commented on packages/dialtone-icons/src/svg/icons/brand/dialpad-sparkle.svg
@fede-dp Gradient direction is incorrect. Should be like attached.

2024-09-13 15:41 UTC, fede-dp commented on packages/dialtone-icons/src/svg/icons/brand/dialpad-sparkle.svg
it's super weird because it's using the gradient style from figma but looks different 🤷🏼‍♂️  i'm uploading the file again just in case

2024-09-13 20:15 UTC, francisrupert approved these changes
Ship it. Follow through on the other Acceptance Criteria of [DLT-1991](https://dialpad.atlassian.net/browse/DLT-1991)

2024-09-13 20:15 UTC, francisrupert commented on packages/dialtone-icons/src/svg/icons/brand/dialpad-sparkle.svg
yep, perfect.

2024-09-16 12:21 UTC, merged