feat(input): DLT-2080 add type search to input
dialpad/dialtone pull request #538
Opened 2024-10-23 14:51 UTC by ninamarina

# PR Title

## Obligatory GIF (super important!)

![Obligatory GIF](path/to/gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ ] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [ ] I have considered how this change will behave on different screen sizes.
- [ ] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

If new component:

- I am exporting any new components or constants:
  - [ ] from the index.js in the component directory.
  - [ ] from the index.js in the root (either `packages/dialtone-vue2` or `packages/dialtone-vue3`).
- [ ] I have added the styles for the new component to the `packages/dialtone-css` package.
- [ ] I have created a page for the new component on the documentation site in `apps/dialtone-documentation`.
- [ ] I have added the new component to `common/components_list.js`
- [ ] I have created a component story in storybook
- [ ] I have created story / stories for any relevant component variants in storybook
- [ ] I have created a docs page for the component in storybook.
- [ ] I have checked that changing all props/slots via the UI in storybook works as expected.

## :crystal_ball: Next Steps

## :camera: Screenshots / GIFs

## :link: Sources

2024-10-24 19:06 UTC, braddialpad approved these changes
Looks good!

2024-10-24 19:08 UTC, braddialpad requested changes

2024-10-24 19:08 UTC, braddialpad commented on apps/dialtone-documentation/docs/components/input.md
Oh, just realized the actual example is not showing a clear button in the input. We probably want to have that right?

2024-10-25 14:31 UTC, ninamarina commented on apps/dialtone-documentation/docs/components/input.md
The button appears when there is text on the input 😅

2024-10-25 15:46 UTC, braddialpad commented on apps/dialtone-documentation/docs/components/input.md
hmm let's maybe populate the search with some text by default then.

2024-10-25 16:21 UTC, braddialpad approved these changes
Just populate search input with text and we're good!

2024-10-28 13:45 UTC, merged