add open prop to hovercard
dialpad/dialtone pull request #597
Opened 2024-12-16 19:18 UTC by ninamarina

# PR Title

## Obligatory GIF (super important!)

![Obligatory GIF](path/to/gif)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

## :book: Description

## :bulb: Context

## :pencil: Checklist

For all PRs:

- [ ] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [ ] I have reviewed my changes.
- [ ] I have added all relevant documentation.
- [ ] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [ ] I have considered how this change will behave on different screen sizes.
- [ ] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

If new component:

- I am exporting any new components or constants:
  - [ ] from the index.js in the component directory.
  - [ ] from the index.js in the root (either `packages/dialtone-vue2` or `packages/dialtone-vue3`).
- [ ] I have added the styles for the new component to the `packages/dialtone-css` package.
- [ ] I have created a page for the new component on the documentation site in `apps/dialtone-documentation`.
- [ ] I have added the new component to `common/components_list.js`
- [ ] I have created a component story in storybook
- [ ] I have created story / stories for any relevant component variants in storybook
- [ ] I have created a docs page for the component in storybook.
- [ ] I have checked that changing all props/slots via the UI in storybook works as expected.

## :crystal_ball: Next Steps

## :camera: Screenshots / GIFs

## :link: Sources

2024-12-17 19:53 UTC, juliodialpad requested changes, later dismissed
Hovercard changes look good, please check my comment about the popover changes.

2024-12-17 19:53 UTC, juliodialpad commented on packages/dialtone-vue2/components/popover/popover.vue
I don't like using 'hovercard' for naming stuff inside `popover` component makes me feel like we're mixing two components, Hovercard should be extending the popover, but we shouldn't need to modify the popover itself

2024-12-17 19:59 UTC, juliodialpad commented
Don't forgot to update the docs on the [HoverCard component page](https://dialtone.dialpad.com/deploy-previews/pr-597/components/hovercard.html)

2024-12-17 21:21 UTC, braddialpad approved these changes
I'm okay with you merging this and then fixing it later since this works, and is probably a blocker for your launch-a-thon team, but I agree with @juliodialpad that it would be ideal to have all hovercard logic in the hovercard component and we should try to do that. I realize popover is a very complicated component and it might take a while.

2024-12-17 21:21 UTC, braddialpad commented on packages/dialtone-vue2/components/popover/popover.vue
I think it should be possible to pass in listeners from the hovercard component and then use v-sync / v-model to manage the "open" prop. Let me know if there is some blocker I am not seeing.

2024-12-18 14:21 UTC, ninamarina commented
> I'm okay with you merging this and then fixing it later since this works, and is probably a blocker for your launch-a-thon team, but I agree with @juliodialpad that it would be ideal to have all hovercard logic in the hovercard component and we should try to do that. I realize popover is a very complicated component and it might take a while.

I created this ticket and added it to the next sprint: https://dialpad.atlassian.net/browse/DLT-2245. Thanks!

2024-12-18 14:29 UTC, ninamarina commented on packages/dialtone-vue2/components/popover/popover.vue
Absolutely agree. I will do those changes in this ticket  https://dialpad.atlassian.net/browse/DLT-2245

2024-12-18 14:30 UTC, merged