DLT-2244: add ability inherit image properties in editor
dialpad/dialtone pull request #604
Opened 2024-12-27 02:22 UTC by emariotti3

# feat(rich-text-editor): add ability inherit image properties in editor

## Obligatory GIF (super important!)

![Obligatory GIF](https://media.giphy.com/media/R6gvnAxj2ISzJdbA63/giphy.gif?cid=790b7611j3tqlmijvz7jqujwg4a4p1mwyqn2k5pv5cpbyw07&ep=v1_gifs_trending&rid=giphy.gif&ct=g)

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

## :book: Jira Ticket

[DLT-2244](https://dialpad.atlassian.net/browse/DLT-2244)

## :book: Description

Tip tap seems to strip the width from inserted images, so we need to add support adjusting image sizing. We found this useful thread [here](https://github.com/ueberdosis/tiptap/issues/4103) showing how to get the tiptap image extension to inherit the attributes from the img html tag.

## :bulb: Context

This is mainly to be able to use it in email reply quotes and perhaps we could use it as well to add the ability to insert inline attachments/images. See short video [here](https://drive.google.com/file/d/1a_lfH2hMUusQeGCwZaYKBG4Pq3bbbRiM/view?usp=sharing) showing the problem.

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

For all Vue changes:

- [x] I have added / updated unit tests.
- [x] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)
- [x] I have validated components with a screen reader.
- [x] I have validated components keyboard navigation.

## :camera: Screenshots / GIFs

<img width="1483" alt="DLT-2244-add-ability-resize-images-editor" src="https://github.com/user-attachments/assets/4c89879d-d0a0-481b-90ab-9dcad2344f40" />

<img width="1496" alt="DLT-2244-add-ability-resize-images-editor-2" src="https://github.com/user-attachments/assets/4325c181-e904-4b96-b36f-2bbcc234ba4c" />

## :link: Sources

Adding the link for the tip-tap [issue](https://github.com/ueberdosis/tiptap/issues/4103) referenced for this change

2024-12-27 18:33 UTC, juliodialpad commented
Hi @emariotti-dialpad Please let me know how to properly test this, I tried just copy pasting an image into the editor and it's just pasting a giant icon. 

![Screenshot 2024-12-27 at 12 33 11 p m](https://github.com/user-attachments/assets/1ee215ee-3231-4ab9-b47f-e307c8701552)

2024-12-27 18:34 UTC, juliodialpad requested changes
The value is not being updated properly on Vue 3, please check that Vue 2 and Vue 3 versions are working properly on storybook.

2024-12-27 18:34 UTC, juliodialpad commented on packages/dialtone-vue3/components/rich_text_editor/rich_text_editor_default.story.vue
> +    v-model="$attrs.value"
This is not correct, the value is defined in the component data on line 43, so it should only be

```suggestion
    v-model="value"
```

we only add the `$attrs` when this is coming from storybook

2024-12-27 18:34 UTC, juliodialpad commented on packages/dialtone-vue3/recipes/conversation_view/editor/editor.vue
> +      class="d-of-auto d-mx16 d-mb4 d-c-text"
Thanks for this fix, haven't noticed this was out of sync between vue 2 and vue 3 versions

2024-12-27 18:34 UTC, juliodialpad commented on packages/dialtone-vue3/recipes/conversation_view/editor/editor_default.story.vue
> +      v-model="$attrs.value"
remove `$attrs`

```suggestion
      v-model="value"
```

2024-12-27 18:34 UTC, juliodialpad commented on packages/dialtone-vue3/recipes/conversation_view/editor/editor_default.story.vue
> +      value: this.$attrs.value,
```suggestion
      value: this.$attrs.modelValue,
```

2024-12-27 20:26 UTC, emariotti3 commented
@juliodialpad I run it locally and set the image tag in the `value` string in the argsData parameter here `packages/dialtone-vue3/recipes/conversation_view/editor/editor.stories.js`

<img width="1242" alt="Screenshot 2024-12-27 at 5 24 04 PM" src="https://github.com/user-attachments/assets/34b00c9e-c12e-4b7b-a0c3-a91940c633a6" />

2024-12-30 18:00 UTC, juliodialpad approved these changes
Thanks! working correctly now

2024-12-30 19:12 UTC, merged